{% set name = "rmf" %}
{% set version = "1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/salilab/rmf/archive/refs/tags/{{ version }}.tar.gz
  sha256: e54c831f63aad2210e5c81c352a81f4c9699e8867cde9c9cd61857713cfd094c

build:
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - swig
    - cmake
    - ninja
  host:
    - python
    - boost-cpp
    - hdf5
  run:
    - python
    - boost-cpp
    - hdf5

test:
  imports:
    - RMF
    - RMF_HDF5
  commands:
    - rmf3_dump --version

about:
  home: https://integrativemodeling.org/rmf/
  summary: Library to support reading and writing of RMF files
  license: Apache-2.0
  license_file: COPYING
  description: |
    This library provides support for the RMF file format for storing
    hierarchical molecular data (such as atomic or coarse grained
    representations of proteins), along with markup, including geometry
    and score data.
  doc_url: https://integrativemodeling.org/rmf/
  dev_url: https://github.com/salilab/rmf/

extra:
  recipe-maintainers:
    - benmwebb
