{% set name = "rmf" %}
{% set version = "1.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/salilab/rmf/archive/refs/tags/{{ version }}.tar.gz
  sha256: abe143e7411b910e5ba863c162b3a23bfdec440cbb1c4909e88727c0e63ad772

build:
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - swig
    - cmake
    - ninja
  host:
    - python
    - numpy
    - libboost-devel
    - hdf5
  run:
    - python
    - hdf5

test:
  imports:
    - RMF
    - RMF_HDF5
  commands:
    - rmf3_dump --version

about:
  home: https://integrativemodeling.org/rmf/
  summary: Library to support reading and writing of RMF files
  license: Apache-2.0
  license_file: COPYING
  description: |
    This library provides support for the RMF file format for storing
    hierarchical molecular data (such as atomic or coarse grained
    representations of proteins), along with markup, including geometry
    and score data.
  doc_url: https://integrativemodeling.org/rmf/
  dev_url: https://github.com/salilab/rmf/

extra:
  recipe-maintainers:
    - benmwebb
