{% set name = "rmf" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/salilab/rmf/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9e885b2342bc0896502ca4fd9c1712103af199b9b6c170b8f004fa82feb94ada

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - swig
    - cmake
    - ninja
  host:
    - python
    - numpy
    - boost-cpp
    - hdf5
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - boost-cpp
    - hdf5

test:
  imports:
    - RMF
    - RMF_HDF5
  commands:
    - rmf3_dump --version

about:
  home: https://integrativemodeling.org/rmf/
  summary: Library to support reading and writing of RMF files
  license: Apache-2.0
  license_file: COPYING
  description: |
    This library provides support for the RMF file format for storing
    hierarchical molecular data (such as atomic or coarse grained
    representations of proteins), along with markup, including geometry
    and score data.
  doc_url: https://integrativemodeling.org/rmf/
  dev_url: https://github.com/salilab/rmf/

extra:
  recipe-maintainers:
    - benmwebb
